### ISSUE TITLE
omgmogomogm big bug

### ISSUE THREAD

**Issue by 3w7** [1x6/box.xenys.net#1]
ogmomOMGOMGMOGMOMOG I FOUND A BUG IM THE FIRST YESSSSSSSSSSS

when u click that gay discord icon it just opens new tab of the site.

**Comment by 3w7** [comment]
https://streamable.com/y0fapk

**Comment by 1x6** [comment]
thanks i know that tho

**Comment by 1x6** [comment]
i dont have a discord yet
